package me.theclashfruit.rithle.modrinth.models

data class Project(
    val slug: String,
    val title: String,
    val description: String,
    val categories: List<String>,
    val client_side: String,
    val server_side: String,
    val body: String,
    val status: String,
    val requested_status: String? = null,
    val additional_categories: List<String>? = null,
    val issues_url: String? = null,
    val source_url: String? = null,
    val wiki_url: String? = null,
    val discord_url: String? = null,
    val donation_urls: List<DonationUrl>? = null,
    val project_type: String,
    val downloads: Int,
    val icon_url: String? = null,
    val color: Int? = null,
    val thread_id: String? = null,
    val monetization_status: String? = null,
    val id: String,
    val team: String,
    val body_url: String? = null,
    val moderator_message: List<ModeratorMessage>? = null,
    val published: String,
    val updated: String,
    val approved: String? = null,
    val queued: String? = null,
    val followers: Int,
    val license: ProjectLicense? = null,
    val versions: List<String>? = null,
    val game_versions: List<String>? = null,
    val loaders: List<String>? = null,
    val gallery: List<GalleryImage>? = null
)
