name: ❓ Question
description: Ask unanswered questions about Rithle.

labels: [question]

body:
  - type: checkboxes
    attributes:
      label: "Please confirm the following:"
      options:
        - label: I have checked the FAQ in [CONTRIBUTING.md](https://github.com/TheClashFruit/Rithle/blob/main/CONTRIBUTING.md).
          required: true
        - label: I have checked for existing issues with similar questions.
          required: true
  - type: textarea
    attributes:
      label: Describe your question
      description: A clear and concise description of your question.
    validations:
      required: true