name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "dev/*" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for Gradlew
      run: chmod +x gradlew
    - name: Add Oauth tokens to local.properties
      run: |
        echo modrinth_client=\"$MODRINTH_CLIENT\" >> local.properties
        echo modrinth_secret=\"$MODRINTH_SECRET\" >> local.properties
      env:
        MODRINTH_CLIENT: ${{ secrets.MODRINTH_CLIENT }}
        MODRINTH_SECRET: ${{ secrets.MODRINTH_SECRET }}
    - name: Build with Gradle
      run: ./gradlew assembleRelease
    - name: Upload APK artifacts
      uses: actions/upload-artifact@v3
      with:
        name: APK artifacts
        path: app/build/outputs/apk/release
